# Generated by Django 5.1.6 on 2025-03-04 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FIR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crime_scene', models.TextField()),
                ('objects_detected', models.JSONField()),
                ('people_detected', models.JSONField()),
                ('extracted_text', models.TextField()),
                ('generated_fir', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
