# Generated by Django 5.1.6 on 2025-03-04 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fir',
            old_name='people_detected',
            new_name='people_identified',
        ),
    ]
